version: "3.7"

services:
  fastify:
    image: node:23.10.0-alpine3.21
    working_dir: /app
    container_name: fastify
    volumes:
      - $PWD:/app
    command: tail -f /dev/null
    ports:
      - 8000:8000

  fastifydb:
    container_name: fastifydb
    image: postgres:18beta1-alpine3.22
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: changeme
      POSTGRES_HOST_AUTH_METHOD: trust
      # PGPORT: 5432
      # PGDATA: ~/Documents/programming/mypostgres
    ports:
      - 5432:5432

  fastifyadmin:
    container_name: fastifyadmin
    image: dpage/pgadmin4:2025-06-25-1
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin4.org
      PGADMIN_DEFAULT_PASSWORD: changeme
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - 8080:80